# rl_bridge_approach experiments in DoorKnobs env.
---
APPROACHES:
  rl_bridge:
    NAME: "rl_bridge_policy"
    FLAGS:
      explorer: "maple_q"
      bilevel_plan_without_sim: True
      mlp_regressor_max_itr: 100000
      segmenter: "oracle"
      demonstrator: "oracle"
      sesame_max_skeletons_optimized: 50
ENVS:
  grid_row:
    NAME: "doorknobs"
ARGS:
  - "debug"
FLAGS:
  max_initial_demos: 0
  sampler_learner: "oracle"
  strips_learner: "oracle"
START_SEED: 0
NUM_SEEDS: 5