# rl_bridge_approach experiments in DoorKnobs env.
---
APPROACHES:
  rl_bridge:
    NAME: "rl_bridge_policy"
    FLAGS:
      explorer: "maple_q"
      bilevel_plan_without_sim: True
      mlp_regressor_max_itr: 100000
      segmenter: "oracle"
      demonstrator: "oracle"
      sesame_max_skeletons_optimized: 50
ENVS:
  doorknobs:
    NAME: "doorknobs"
ARGS:
  - "debug"
FLAGS:
  max_initial_demos: 0
  sampler_learner: "oracle"
  strips_learner: "oracle"
  num_online_learning_cycles: 100
  num_test_tasks: 1
  num_train_tasks: 1
  interactive_num_requests_per_cycle: 5
  online_nsrt_learning_requests_per_cycle: 5
  timeout: 1000
  active_sampler_learning_num_samples: 10
START_SEED: 0
NUM_SEEDS: 4