# Learning operators, samplers, policies, and predicates.
---
APPROACHES:
  learn_all:
    NAME: "grammar_search_invention"
    FLAGS:
      min_perc_data_for_nsrt: 1
      segmenter: "contacts"
      neural_gaus_regressor_max_itr: 50000
      sesame_max_samples_per_step: 100  # mainly to improve demo collection
ENVS:
  cover:
    NAME: "coffee"
ARGS: []
FLAGS:
  num_train_tasks: 10
  excluded_predicates: "all"
  timeout: 300
  grammar_search_grammar_use_diff_features: False
  grammar_search_grammar_use_euclidean_dist: False
  grammar_search_grammar_includes_givens: True
START_SEED: 456
NUM_SEEDS: 1
...
