# Config file for generating the mara_bench videos
# Excample run: 
#    python scripts/local/launch_simp.py -c mara_bench.yaml
---
APPROACHES:
  oracle:
    NAME: "oracle"
    # FLAGS:
    # ARGS:

ENVS:
  # blocks:
  #   NAME: "pybullet_blocks"
  # blocks_cf:
  #   NAME: "pybullet_blocks"
  #   FLAGS:
  #     blocks_high_towers_are_unstable: True
  # cover_cf:
  #   NAME: "pybullet_cover"
  #   FLAGS:
  #     cover_blocks_change_color_when_cover: True
  # cover:
  #   NAME: "pybullet_cover"
  # coffee:
  #   NAME: "pybullet_coffee"
  #   FLAGS:
  #     coffee_rotated_jug_ratio: 0
  #     sesame_check_expected_atoms: False
  #     coffee_machine_have_light_bar: False
  #     coffee_move_back_after_place_and_push: True
  #     coffee_machine_has_plug: True
  #     option_model_terminate_on_repeat: False
  #     coffee_use_pixelated_jug: True
  #     pybullet_ik_validate: False
  #     sesame_max_skeletons_optimized: 1
  # coffee_cf:
  #   NAME: "pybullet_coffee"
  #   FLAGS:
  #     coffee_plug_break_after_plugged_in: True
  #     coffee_rotated_jug_ratio: 0
  #     sesame_check_expected_atoms: False
  #     coffee_machine_have_light_bar: False
  #     coffee_move_back_after_place_and_push: True
  #     coffee_machine_has_plug: True
  #     option_model_terminate_on_repeat: False
  #     coffee_use_pixelated_jug: True
  #     pybullet_ik_validate: False
  #     sesame_max_skeletons_optimized: 1
  balance:
    NAME: "pybullet_balance"
    FLAGS:
      excluded_predicates: "Balanced,OnPlate"
      sesame_max_skeletons_optimized: 1
      sesame_check_expected_atoms: False
      pybullet_ik_validate: False


ARGS:
  - "debug"
  - "use_gui"
  - "make_demo_videos"
  - "make_failure_videos"
  - "make_test_videos"
FLAGS:
  # This is particularly useful in some envs. In blocks with high towers are
  # unstable, this is useful to capture the unstability and to avoid force from
  # the prev. episode to affect the current episode.
  terminate_on_goal_reached: False
  num_train_tasks: 1
  num_test_tasks: 1
  video_fps: 20
  pybullet_camera_height: 900
  pybullet_camera_width: 900
  use_counterfactual_dataset_path_name: True
  keep_failed_demos: True
START_SEED: 0
NUM_SEEDS: 1
# 