# Config file for running the counterfactual classification problems.
# Excample run: 
#    python scripts/local/launch_simp.py -c mara_bench_clf.yaml
---
APPROACHES:
  # vlm_clf:
  #   NAME: "vlm_classification"
  dino_sim:
    NAME: "dino_similarity"
    FLAG:
      dino_model_name: "dinov2_vits14"
      distance_function: "dtw"

ENVS:
  cover:
    NAME: "pybullet_cover"

ARGS:
  - "debug"
  - "use_gui"
  - "make_demo_videos"
  # - "make_demo_images"
  - "make_failure_videos"
  - "make_test_videos"
FLAGS:
  # This is particularly useful in some envs. In blocks with high towers are
  # unstable, this is useful to capture the unstability and to avoid force from
  # the prev. episode to affect the current episode.
  terminate_on_goal_reached: False
  num_train_tasks: 1
  num_test_tasks: 1
  video_fps: 20
  pybullet_camera_height: 900
  pybullet_camera_width: 900
  use_counterfactual_dataset_path_name: True
  use_classification_problem_setting: True # Choose entry point
  classification_has_counterfactual_support: False
  keep_failed_demos: True
  vlm_model_name: "gemini-2.0-pro-exp-02-05"
  # vlm_model_name: "gpt-4o"
  vlm_temperature: 0.2
  log_file: "yes" # if not empty, logs will be saved
START_SEED: 2
NUM_SEEDS: 1
USE_GPU: True