# Config file for running the counterfactual classification problems.
# Excample run: 
#    python scripts/local/launch_simp.py -c mara_bench_clf.yaml
---
APPROACHES:
  vlm_clf:
    NAME: "vlm_classification"
  # dino_sim_dtw:
  #   NAME: "dino_similarity"
  #   FLAG:
  #     dino_model_name: "dinov2_vitg14_reg"
  #     # dino_model_name: "dinov2_vits14"
  #     distance_function: "dtw"
  # dino_sim_chamfer:
  #   NAME: "dino_similarity"
  #   FLAG:
  #     dino_model_name: "dinov2_vitg14_reg"
  #     distance_function: "chamfer"

ENVS:
  all:
    NAME: "all_tasks"

ARGS:
  - "debug"
FLAGS:
  log_file: "yes" # if not empty, logs will be saved
  use_classification_problem_setting: True
  classification_has_counterfactual_support: False

  # VLM approach configs
  vlm_model_name: "gemini-2.0-pro-exp-02-05"
  # vlm_model_name: "gpt-4o"
  vlm_temperature: 0.2
START_SEED: 0
NUM_SEEDS: 3
USE_GPU: True