# Predicate invention slowness tests
---
APPROACHES:
  invent_with_noise_awareness:
    NAME: "grammar_search_invention"
    FLAGS:
      strips_learner: "cluster_and_intersect"
      excluded_predicates: "all"
      grammar_search_predicate_labelling_noise_prob: 0.01
      disable_harmlessness_check: True
      cluster_and_intersect_min_datastore_fraction: 0.1
ENVS:
  cover:
    NAME: "cover"
  painting:
    NAME: "painting"
  # blocks:
  #   NAME: "blocks"
  # tools:
  #   NAME: "tools"
ARGS: []
FLAGS:
  num_train_tasks: 200
START_SEED: 456
NUM_SEEDS: 10
...
