# Predicate invention with pnad_search operator learning
---
APPROACHES:
  invent_allexclude_backchaining:
    NAME: "grammar_search_invention"
    FLAGS:
      strips_learner: "pnad_search"
      excluded_predicates: "all"
ENVS:
  # cover:
  #   NAME: "cover"
  # pybullet_blocks:
  #   NAME: "pybullet_blocks"
  # painting:
  #   NAME: "painting"
  # tools:
  #   NAME: "tools"
  #   FLAGS:
  #     num_train_tasks: 200  # requires more data (default is 50)
  # pybullet_cover:
  #   NAME: "pybullet_cover"
  cluttered_1d:
    NAME: "repeated_nextto_single_option"
ARGS: []
FLAGS: {}
START_SEED: 456
NUM_SEEDS: 10
...
