# Predicate invention slowness tests
---
APPROACHES:
  invent_allexclude_backchaining:
    NAME: "grammar_search_invention"
    FLAGS:
      strips_learner: "cluster_and_intersect"
      excluded_predicates: "all"
      grammar_search_grammar_use_diff_features: True
      grammar_search_max_predicates: 1500
      grammar_search_predicate_cost_upper_bound: 25
      num_train_tasks: 50
      num_test_tasks: 50
      grammar_search_grammar_use_euclidean_dist: True
      sesame_max_skeletons_optimized: 1000

ENVS:
  rnt_simple:
    NAME: "stick_button_move"
ARGS: []
FLAGS: {}
START_SEED: 456
NUM_SEEDS: 10
...
