# Final rl_bridge_approach experiments.
---
APPROACHES:
  rl_bridge:
    NAME: "rl_bridge_policy"
    FLAGS:
      explorer: "maple_q"
      bilevel_plan_without_sim: True
      mlp_regressor_max_itr: 100000
      segmenter: "oracle"
      demonstrator: "oracle"
      sesame_max_skeletons_optimized: 50
ENVS:
  grid_row_door:
    NAME: "grid_row_door"
    FLAGS:
      max_num_steps_interaction_request: 100
      interactive_num_requests_per_cycle: 5
      online_nsrt_learning_requests_per_cycle: 5
      num_online_learning_cycles: 100
      num_test_tasks: 1
      num_train_tasks: 1
      grid_row_num_cells: 6
ARGS:
  - "debug"
FLAGS:
  max_initial_demos: 0
  sampler_learner: "oracle"
  strips_learner: "oracle"
START_SEED: 1
NUM_SEEDS: 3