---
APPROACHES:
  supervised-predicate-learning:
    NAME: "interactive_learning"
    FLAGS:
      excluded_predicates: "all-including-goals"
      num_train_tasks: 100
      interactive_num_ensemble_members: 1
ENVS:
  sokoban:
    NAME: "sokoban"
    FLAGS:
      sokoban_gym_name: "Sokoban-small-v0"
      sesame_task_planner: "fdopt"
      bilevel_plan_without_sim: True
      disable_harmlessness_check: True
      mlp_classifier_balance_data: False
      teacher_dataset_num_examples: 100000000  # upper bound
ARGS: []
FLAGS: 
  timeout: 60
START_SEED: 456
NUM_SEEDS: 1
...
