---
APPROACHES:
  oracle:
    NAME: "oracle"
  nsrt_learning-25:
    NAME: "nsrt_learning"
    FLAGS:
      num_train_tasks: 25
  nsrt_learning-50:
    NAME: "nsrt_learning"
    FLAGS:
      num_train_tasks: 50
  nsrt_learning-100:
    NAME: "nsrt_learning"
    FLAGS:
      num_train_tasks: 100
  nsrt_learning-250:
    NAME: "nsrt_learning"
    FLAGS:
      num_train_tasks: 250
  nsrt_learning-500:
    NAME: "nsrt_learning"
    FLAGS:
      num_train_tasks: 500
  nsrt_learning-1000:
    NAME: "nsrt_learning"
    FLAGS:
      num_train_tasks: 1000
ENVS:
  sokoban:
    NAME: "sokoban"
    FLAGS:
      sokoban_gym_name: "Sokoban-small-v0"
      sesame_task_planner: "fdopt"
      bilevel_plan_without_sim: "True"
      disable_harmlessness_check: "True"
ARGS: []
FLAGS: {}
START_SEED: 456
NUM_SEEDS: 5
...
