# Use VLM to propose predicates.
---
APPROACHES:
  learn_all:
    NAME: "vlm_online_invention"
    FLAGS: []
ENVS:
  stick_button:
    # NAME: "stick_button"
    # NAME: "cover_place_hard"
    # NAME: "pybullet_cover"
    NAME: "pybullet_blocks"
    # NAME: "blocks"
    # NAME: "doors"
    # NAME: "sokoban"
    # NAME: "sandwich"
    # NAME: "screws"
    # NAME: "sticky_table"
    # NAME: "painting"
    # NAME: "tools"
    # NAME: "coffee"
    # NAME: "playroom_simple"
    
ARGS: 
  # []
  - "debug"
  # - "rgb_observation" # stick_button doesn't support rendering
  # - "make_segmented_demo_videos"
  # - "make_demo_videos" 
  # - "use_gui"
  # - "load_approach"
FLAGS:
  num_train_tasks: 5
  num_test_tasks: 20
  option_learner: no_learning # include all options by flagging no learning
  sampler_learner: oracle
  strips_learner: "cluster_and_intersect"
  # bilevel_plan_without_sim: True
  # excluded_predicates: "'Grasped,StickAboveButton'"
  excluded_predicates: "all"
  sesame_max_samples_per_step: 10
  min_perc_data_for_nsrt: 10
  segmenter: "option_changes"
  neural_gaus_regressor_max_itr: 50000
  timeout: 30 #300
  pybullet_camera_width: 800
  pybullet_camera_height: 900
  video_fps: 20

  # Env settings
  rgb_observation: False
  render_init_state: True # True for NSP

  # Predicate refinement parameters
  grammar_search_search_algorithm: "gbfs"
  grammar_search_predicate_cost_upper_bound: 10
  # grammar_search_search_algorithm: "hill_climbing"
  painting_raise_environment_failure: False
  grammar_search_grammar_use_single_feature: False
  grammar_search_grammar_use_skip_grammar: False
  grammar_search_grammar_includes_negation: False # relaxation 2
  grammar_search_grammar_includes_foralls: False  # relaxation 2
  load_llm_pred_invent_dataset: False
  save_llm_pred_invent_dataset: False # can't pickle rendered states

  # NSP (using VLMs) setting
  neu_sym_predicate: True # True for NSP
  save_nsp_image_patch_before_query: False
  vlm_model_name: "gemini-1.5-pro"
  vlm_temperature: 0
  vlm_use_chat_mode: True
  sesame_check_expected_atoms: False
  query_vlm_for_each_assertion: False
  query_vlm_for_each_predicate: False
  llm_openai_max_response_tokens: 4096
  llm_predicator_use_grammar: True # always true?
  vlm_predicator_oracle_base_grammar: False
  llm_predicator_oracle_learned: False            # relaxation 1
  vlm_predicator_render_option_state: True # True for NSP
  # Test
  grammar_search_prune_redundant_preds: False
START_SEED: 2
NUM_SEEDS: 1
...
