# Use VLM to propose predicates.
---
APPROACHES:
  learn_all:
    NAME: "vlm_online_invention"
    FLAGS: []
ENVS:
  stick_button:
    # NAME: "stick_button"
    # NAME: "cover_place_hard"
    # NAME: "pybullet_cover"
    NAME: "pybullet_blocks"
    # NAME: "blocks"
    # NAME: "doors"
    # NAME: "sokoban"
    # NAME: "sandwich"
    # NAME: "screws"
    # NAME: "sticky_table"
    # NAME: "painting"
    # NAME: "tools"
    # NAME: "coffee"
    # NAME: "playroom_simple"
    
ARGS: 
  # []
  - "debug"
  # - "rgb_observation" # stick_button doesn't support rendering
  # - "make_segmented_demo_videos"
  # - "make_demo_videos" 
  # - "use_gui"
  # - "load_approach"
FLAGS:
  num_train_tasks: 10
  num_test_tasks: 50
  # option_learner: direct_bc # So it doesn' include all oracle options in init
                            # when including all options, should also include
                            # all predicates.
  option_learner: no_learning # include all options by flagging no learning
  sampler_learner: oracle
  strips_learner: "cluster_and_intersect"
  # bilevel_plan_without_sim: True
  # excluded_predicates: "'Grasped,StickAboveButton'"
  excluded_predicates: "all"
  sesame_max_samples_per_step: 10
  min_perc_data_for_nsrt: 3
  segmenter: "option_changes"
  neural_gaus_regressor_max_itr: 50000
  vlm_model_name: "gpt-3.5-turbo-0125"
  timeout: 300
  pybullet_camera_width: 1674 
  pybullet_camera_height: 900
  video_fps: 20
  # grammar_search_search_algorithm: "hill_climbing"
  grammar_search_search_algorithm: "gbfs"
  painting_raise_environment_failure: False
  grammar_search_grammar_use_single_feature: False
  grammar_search_grammar_use_skip_grammar: False

  llm_predicator_use_grammar: False
  llm_predicator_oracle_base: False
  llm_predicator_oracle_learned: True
  vlm_predicator_render_option_state: True
  vlm_use_chat_mode
START_SEED: 2
NUM_SEEDS: 1
...
