"""Agent model-based explorer: the agent sketches an experiment against the
learned belief model, and it runs as written.

Queries a Claude agent for a fully parameterized plan sketch and rolls
it out for real exactly as written. The agent refines and validates
in-session against the currently-learned belief model (``sim.refine``,
``sim.run``, ``submit_plan``); a plan that passed the capture
gate executes as a belief-certified solve attempt, anything else
executes as an experiment with no harness-side parameter search or
substitution. When the belief model disagrees with reality (e.g. a
subgoal atom it expected after a Wait doesn't actually hold), the
trajectory is a targeted learning signal for online simulator
synthesis.

Parallels ``AgentModelBasedApproach`` for the sketch workflow; the
session plumbing lives in ``AgentExplorerBase``.

Registered under the CLI explorer name ``agent_model_based``
(``agent_bilevel`` is kept as a deprecated alias).
"""

import logging
import os
from typing import Any, Callable, Dict, List, Optional, Sequence

import numpy as np

from predicators import utils
from predicators.agent_sdk import bilevel_sketch
from predicators.agent_sdk.rendering import save_task_state_image
from predicators.agent_sdk.session_base import AgentSessionFatalError, \
    query_fatal_error
from predicators.agent_sdk.session_manager import run_query_sync
from predicators.agent_sdk.tools import PlanCapture, agent_render_resolution, \
    load_ground_sampler_fns
from predicators.explorers.agent_explorer_base import AgentExplorerBase
from predicators.settings import CFG
from predicators.structs import Action, ExplorationStrategy, State, Task


class AgentModelBasedExplorer(AgentExplorerBase):
    """Queries a Claude agent for a plan sketch and executes it as written."""

    @classmethod
    def get_name(cls) -> str:
        return "agent_model_based"

    # ------------------------------------------------------------------ #
    # Exploration strategy
    # ------------------------------------------------------------------ #

    def _get_exploration_strategy(self, train_task_idx: int,
                                  timeout: int) -> ExplorationStrategy:
        task = self._train_tasks[train_task_idx]
        # The approach syncs tool_context.option_model right before building
        # this explorer, so reading here picks up the latest learned model.
        option_model = self._tool_context.option_model
        assert option_model is not None, \
            "agent_model_based explorer needs a synced option_model"

        # Reset the per-request mental-model verdict so a stale value can't
        # leak if the query below throws or falls back to random before
        # producing one.
        self._tool_context.last_mental_model_solved = None

        # Point the agent's interactive tools (submit_plan, the
        # sim probe) at the EXPLORE task. They
        # default to ctx.current_task when the agent omits task_idx, and
        # test-time _solve leaves current_task on the last TEST task.
        # Without this the agent tunes/validates its exploration plan against
        # the wrong task (e.g. a test goal referencing objects this task
        # lacks), so parameter search is meaningless and only tasks solvable
        # without tuning get solved.
        #
        # Enable the capture path too (keyed to current_task == this explore
        # task): the agent often submits + simulator-validates a goal-reaching
        # plan via submit_plan but ends with a
        # prose summary whose final text doesn't parse into a sketch. Without
        # capture that productive solve is lost to the random-options fallback;
        # with it we recover the captured plan below (see _sketch_from_capture)
        # and execute it at its captured params. Clear any
        # stale capture first; the next test _solve re-points current_task and
        # clears capture again, so an exploration plan can't leak into a test
        # solve.
        self._tool_context.current_task = task
        self._tool_context.capture_goal_reaching_plans = True
        # Exploration delivers plan sketches even in policy-mode configs:
        # make sure a solve attempt's policy_capture_mode never bleeds
        # into this query (it would disable the plan capture gate).
        self._tool_context.policy_capture_mode = False
        self._tool_context.clear_plan_capture()

        try:
            prompt = bilevel_sketch.build_solve_prompt(
                task,
                all_predicates=self._predicates,
                all_options=self._options,
                trajectory_summary=self._build_trajectory_summary(),
                tool_names=self._agent_tool_names(),
                experiment_guidance=self._build_experiment_guidance(),
                # Plans generated by this cycle's earlier requests: ask for a
                # complementary plan instead of the identical one repeated.
                scheduled_plans=list(self._tool_context.cycle_scheduled_plans),
                initial_image_section=self._initial_image_section(
                    task, train_task_idx),
                propose_params=CFG.agent_bilevel_use_llm_initial_params,
                # The sketch is the experiment; a capture-gate-validated
                # plan is welcome (it counts as a solve) but not required.
                require_tool_validation=False,
                # Explore contract: the sketch is a real-env experiment, and
                # the belief model may lack goal-critical dynamics, so a
                # simulator-failing sketch is a valid deliverable.
                explore_mode=True,
            )
            responses = run_query_sync(self._agent_session,
                                       prompt,
                                       kind="explore")
            dead = query_fatal_error(responses)
            if dead is not None:
                # The session backend refused the query (usage limit,
                # auth, transport): a random-options episode here would
                # be junk data that the cycle then learns from (2026-08-28
                # run_20260827_171610 cycle 3). Terminate the run instead;
                # the relaunch re-explores this cycle.
                raise AgentSessionFatalError(
                    "explore query died without the agent doing any work "
                    f"({dead}); not falling back to random exploration.")
            plan_text = self._extract_option_plan_text(responses)
            # The session's tool capture: a goal-reaching plan the agent
            # validated in the belief through the capture gate
            # (submit_plan, N fresh
            # rollouts). ``reached_goal`` is the gate's verdict.
            capture = self._tool_context.take_plan_capture()
            if CFG.agent_explorer_execute_certified_plan and capture.plan \
                    and capture.reached_goal is True:
                # Certified: the mental model solves the task with THIS
                # plan, so run it verbatim as a solve attempt instead of
                # re-searching (or boundary-probing) its parameters. A
                # real success now counts for early stopping. The cycle's
                # later requests see it under "plans already scheduled"
                # and are asked for a DIFFERENT certified plan (a second
                # test of the model), resubmitting this one only as a
                # last resort.
                plan = list(capture.plan)
                logging.info(
                    "agent_model_based explorer: the agent's tool-validated "
                    "plan passed the belief's capture gate (%s); executing "
                    "it verbatim as this episode's solve attempt (mental "
                    "model solved the goal).", capture.validation_summary
                    or "goal reached")
                if capture.sketch:
                    self._tool_context.last_sketch_subgoals = [
                        (s.subgoal_atoms, s.subgoal_neg_atoms)
                        for s in capture.sketch
                    ]
                    self._tool_context.last_sketch_options = [
                        (s.option.name, [o.name for o in s.objects])
                        for s in capture.sketch
                    ]
                self._tool_context.last_mental_model_solved = True
                self._tool_context.cycle_scheduled_plans.append(
                    self._format_plan(plan) +
                    "\n  NOTE: belief-certified; executes verbatim as a "
                    "solve attempt.")
                return self._certified_plan_strategy(plan)
            if not plan_text and not capture.plan:
                raise ValueError("agent returned empty plan text")

            gs_fns, gs_err = load_ground_sampler_fns(self._tool_context)
            if gs_err is not None:
                logging.warning("[explore] %s", gs_err)
            sketch = bilevel_sketch.parse_sketch_from_text(
                plan_text,
                task,
                predicates=self._predicates,
                options=self._options,
                types=self._types,
                parse_continuous_params=CFG.
                agent_bilevel_use_llm_initial_params,
                parse_ground_samplers=CFG.agent_bilevel_ground_samplers,
                ground_sampler_fns=gs_fns or None,
            ) if plan_text else []
            if not sketch:
                sketch = self._sketch_from_capture(capture) or []
            if not sketch:
                raise ValueError("parsed empty plan sketch")
            self._tool_context.last_sketch_subgoals = [
                (s.subgoal_atoms, s.subgoal_neg_atoms) for s in sketch
            ]
            self._tool_context.last_sketch_options = [
                (s.option.name, [o.name for o in s.objects]) for s in sketch
            ]
            # The agent's sketch IS the experiment: it runs in the real
            # environment exactly as written. The harness does no belief
            # refinement of it - the agent refines and validates
            # in-session (sim.refine / sim.run / submit_plan),
            # and only a capture-gate-certified plan (handled above)
            # counts as a belief-validated solve for early stopping.
            plan = self._ground_sketch_verbatim(sketch)
            self._tool_context.last_mental_model_solved = False
            record = self._format_sketch(sketch, plan)
            logging.info(
                "agent_model_based explorer: executing the agent's sketch "
                "verbatim for train task %d (%d steps; not "
                "belief-certified):\n%s", train_task_idx, len(plan), record)
            self._tool_context.cycle_scheduled_plans.append(
                record + "\n  NOTE: executes as written, without "
                "belief-model certification.")
            policy = utils.option_plan_to_policy(
                plan,
                abstract_function=lambda s: utils.abstract(
                    s, self._predicates))
            return self._wrap_policy(policy), lambda _: False
        except AgentSessionFatalError:
            # A random fallback would hide the broken session backend;
            # re-raise so the run terminates.
            raise
        except Exception as e:  # pylint: disable=broad-except
            logging.warning(f"agent_model_based explorer failed: {e}. "
                            "Falling back to random options.")

        if not CFG.agent_explorer_fallback_to_random:
            raise utils.RequestActPolicyFailure(
                "agent_model_based explorer failed and fallback disabled.")
        return self._random_options_fallback()

    # ------------------------------------------------------------------ #
    # Helpers
    # ------------------------------------------------------------------ #

    def _sketch_from_capture(
            self,
            capture: PlanCapture) -> Optional[List[bilevel_sketch.SketchStep]]:
        """Rebuild a sketch from a captured, tool-validated plan, or None.

        ``submit_plan`` stashes a forward-validated plan on the explore
        task into ``solved_plan`` (grounded options with continuous
        params) and ``solved_sketch`` (the option skeleton plus the
        subgoals that actually held). We reconstruct a sketch from that
        skeleton and graft each captured option's continuous params onto
        the step's ``initial_params``, so the plan executes at exactly
        the values the agent validated. The capture was already taken
        (consumed) by the caller.
        """
        plan = capture.plan
        captured_sketch = capture.sketch
        if not plan or not captured_sketch:
            return None
        seeded: List[bilevel_sketch.SketchStep] = []
        for i, step in enumerate(captured_sketch):
            params = None
            if i < len(plan):
                params = np.asarray(plan[i].params, dtype=np.float32)
            seeded.append(
                bilevel_sketch.SketchStep(
                    option=step.option,
                    objects=step.objects,
                    subgoal_atoms=step.subgoal_atoms,
                    subgoal_neg_atoms=step.subgoal_neg_atoms,
                    initial_params=params))
        logging.info(
            "agent_model_based explorer: final text didn't parse, recovered "
            "the "
            "agent's tool-validated plan from capture (%d steps); executing "
            "it at the captured params.", len(seeded))
        return seeded

    def _ground_sketch_verbatim(
            self, sketch: Sequence[bilevel_sketch.SketchStep]) -> List[Any]:
        """Ground each sketch step at the agent's proposed parameters.

        Nothing is searched or substituted: the executed plan is the
        agent's. A step left without parameters (or with the wrong
        arity) gets ONE uniform draw from the option's box and a
        warning. Wait steps carry their annotated subgoals as
        ``wait_target_atoms`` so the option terminates on the intended
        atom change.
        """
        plan: List[Any] = []
        for i, step in enumerate(sketch):
            dim = step.option.params_space.shape[0]
            params = step.initial_params
            if params is None or len(params) != dim:
                if dim > 0:
                    logging.warning(
                        "agent_model_based explorer: step %d (%s) has no "
                        "usable proposed params (%s); drawing one sample "
                        "from the option's box - propose every "
                        "parameter explicitly.", i, step.option.name,
                        None if params is None else list(params))
                params = bilevel_sketch.sample_params(step.option, self._rng)
            plan.append(
                bilevel_sketch.ground_step(
                    step, np.asarray(params, dtype=np.float32)))
        return plan

    @staticmethod
    def _format_sketch(sketch: Sequence[bilevel_sketch.SketchStep],
                       plan: Sequence[Any]) -> str:
        """One indented ``i: Option(objs)[params] -> {atoms}`` line per
        grounded step (params as executed, atoms as annotated)."""
        lines = []
        for i, (step, opt) in enumerate(zip(sketch, plan)):
            objs = ", ".join(o.name for o in opt.objects)
            par = ", ".join(f"{p:.4f}" for p in opt.params)
            line = f"  {i}: {opt.name}({objs})[{par}]"
            atoms = sorted(str(a) for a in (step.subgoal_atoms or set()))
            atoms += sorted(f"NOT {a}"
                            for a in (step.subgoal_neg_atoms or set()))
            if atoms:
                line += f" -> {{{', '.join(atoms)}}}"
            lines.append(line)
        return "\n".join(lines)

    @staticmethod
    def _format_plan(plan: Sequence[Any]) -> str:
        """One indented ``i: Option(objs)[params]`` line per grounded
        option."""
        lines = []
        for i, opt in enumerate(plan):
            obj_s = ", ".join(o.name for o in opt.objects)
            par_s = ", ".join(f"{p:.4f}" for p in opt.params)
            lines.append(f"  {i}: {opt.name}({obj_s})[{par_s}]")
        return "\n".join(lines)

    def _certified_plan_strategy(self,
                                 plan: Sequence[Any]) -> ExplorationStrategy:
        """Execute a belief-certified grounded plan verbatim."""
        logging.info("agent_model_based explorer: certified plan:\n%s",
                     self._format_plan(plan))
        policy = utils.option_plan_to_policy(
            list(plan),
            abstract_function=lambda s: utils.abstract(s, self._predicates))
        return self._wrap_policy(policy), lambda _: False

    def _wrap_policy(
            self, policy: Callable[[State],
                                   Action]) -> Callable[[State], Action]:
        """Convert OptionExecutionFailure into RequestActPolicyFailure.

        Lets the main loop cleanly terminate the episode when the
        refined plan finishes or fails mid-execution (which is exactly
        the disagreement signal we want to collect).
        """

        def _wrapped(state: State) -> Action:
            try:
                return policy(state)
            except utils.OptionExecutionFailure as e:
                raise utils.RequestActPolicyFailure(e.args[0], e.info) from e

        return _wrapped

    def _initial_image_section(self, task: Task, train_task_idx: int) -> str:
        """Render the explore task's initial state and return a prompt section
        pointing at it, mirroring what test-time solves get.

        Saved as ``train_task{N:03d}_initial_state.png`` so train-task
        scenes are inspectable alongside the test-task init images.
        Empty string when rendering is unavailable (e.g. the sandbox
        isn't created yet, so ``image_save_dir`` is unset).
        """
        env = self._tool_context.env
        save_dir = self._tool_context.image_save_dir
        if env is None or save_dir is None:
            return ""
        img_name = f"train_task{train_task_idx:03d}_initial_state.png"
        with agent_render_resolution():
            saved = save_task_state_image(env, task, save_dir, img_name)
        if saved is None:
            return ""
        # cwd of the agent is the sandbox root, so reference test_images/.
        return ("\n## Initial State Image\n"
                "A rendering of the initial scene has been saved to "
                f"`./test_images/{img_name}`. **Read this image first** to "
                "understand the spatial layout before planning.\n")

    def _build_experiment_guidance(self) -> str:
        """LLM-proposal half of active-experiment design.

        Always injects the learn phase's open-questions ledger (the
        ranked experiment specs it wrote for exploration to run) when
        one exists in the sandbox. When info-seeking is on, additionally
        point the agent at ``sim.suggest_probes`` and - when an ensemble
        scorer is wired - at the predicates the learned model is
        currently most internally uncertain about.
        """
        parts = []
        ledger = self._read_open_questions()
        if ledger:
            parts.append(
                "The learning phase left this ranked ledger of OPEN "
                "QUESTIONS - uncertainties it could not settle from the "
                "data collected so far, each with the experiment that "
                "would settle it. The TOP entry is mandatory for this "
                "cycle: run its experiment as specified (its option "
                "sequence and parameters) unless a plan already "
                "scheduled this cycle covers it, and fold in as many "
                "lower entries as the step budget allows:\n" + ledger)
        if CFG.agent_explorer_info_seeking:
            parts.append(
                "Your explicit continuous parameters execute exactly as "
                "written. To find the parameters a step could be run at "
                "to teach the model most, call "
                "`sim.suggest_probes(plan_text)`: it rolls your sketch "
                "forward on your own parameters and, per annotated step, "
                "ranks feasible alternatives by the learned model's "
                "ensemble disagreement on the step's subgoal atoms. Adopt "
                "one by writing it into your sketch, only on a step whose "
                "failure the episode can afford; annotate steps with the "
                "geometry/timing you are least sure the model has right.")
            disagreement = self._build_disagreement_summary()
            if disagreement:
                parts.append(disagreement)
        # System-ID gaps from the previous learn phase (synced by the
        # sim-learning approach): what the collected data could NOT
        # support, phrased as experiment objectives. Exploration is the
        # only place those gaps can be filled.
        sysid = getattr(self._tool_context, "sysid_diagnostics", None)
        if sysid:
            parts.append(
                "The previous system-identification fit left gaps that "
                "only new interaction data can close:\n" + sysid)
        return "\n\n".join(parts)

    _MAX_OPEN_QUESTIONS_CHARS = 4000

    def _read_open_questions(self) -> str:
        """The learn phase's ./open_questions.md ledger, or "".

        The ledger is ranked, so on overflow the head is kept. Read
        directly from the sandbox instead of asking the session to go
        find it: the explore query should START from the ledger, not
        spend its budget rediscovering it.
        """
        sandbox_dir = self._tool_context.sandbox_dir
        if not sandbox_dir:
            return ""
        path = os.path.join(sandbox_dir, "open_questions.md")
        try:
            with open(path, "r", encoding="utf-8") as f:
                text = f.read().strip()
        except OSError:
            return ""
        if len(text) > self._MAX_OPEN_QUESTIONS_CHARS:
            # Cut at an entry boundary, never mid-sentence, and point at
            # the file: a mid-sentence cut silently dropped the entries
            # the header told the agent to fold in (run_20260830).
            head = text[:self._MAX_OPEN_QUESTIONS_CHARS]
            cut = head.rfind("\n#")
            if cut <= 0:
                cut = head.rfind("\n\n")
            if cut > 0:
                head = head[:cut]
            text = (head.rstrip() +
                    "\n[... ledger truncated at the prompt cap - read "
                    "./open_questions.md for the remaining entries]")
        return text

    def _build_disagreement_summary(self) -> str:
        """Name the predicates the ensemble disagrees most about.

        Scans a bounded sample of recent-trajectory states, scores each
        abstract atom's ensemble disagreement via the wired scorer, and
        reports the highest-disagreement predicates. Grounded in the
        actual ensemble, so it points the agent at genuinely-uncertain
        dynamics rather than guesses. Empty when no scorer/trajectories.
        """
        fn = self._tool_context.atom_disagreement_fn
        if fn is None:
            return ""
        all_trajs = (self._tool_context.offline_trajectories +
                     self._tool_context.online_trajectories)
        if not all_trajs:
            return ""
        recent = all_trajs[-CFG.agent_sdk_max_trajectories_in_context:]
        states: List[State] = []
        for traj in recent:
            n = len(traj.states)
            if n == 0:
                continue
            stride = max(1, n // 6)  # <= ~6 states/trajectory to bound cost
            states.extend(traj.states[::stride])
        best: Dict[str, float] = {}
        for s in states:
            for atom in utils.abstract(s, self._predicates):
                try:
                    d = float(fn(s, {atom}))
                except Exception:  # pylint: disable=broad-except
                    continue
                name = atom.predicate.name
                if d > best.get(name, 0.0):
                    best[name] = d
        # One log line with the full ranking (scope note: abstract() yields
        # true atoms only, so a predicate absent here was never measured, not
        # necessarily agreed-upon). All values <= 0.05 -> no guidance: the
        # ensemble is internally confident (or too tight) everywhere.
        all_ranked = sorted(((v, k) for k, v in best.items()), reverse=True)
        logging.info(
            "agent_model_based explorer: per-predicate max ensemble "
            "disagreement "
            "over %d states - %s.", len(states),
            ", ".join(f"{k}={v:.4f}" for v, k in all_ranked) or "(none)")
        ranked = [(v, k) for v, k in all_ranked if v > 0.05][:4]
        if not ranked:
            return ""
        named = ", ".join(f"{k} (disagreement {v:.2f})" for v, k in ranked)
        return ("Across recent trajectories, the learned model is most "
                f"internally uncertain about: {named}. A sketch that puts "
                "these predicates on the critical path will be most "
                "informative.")
