"""A subclass's hidden state must survive the same paths as its physics."""
# pylint: disable=protected-access
import copy
import pickle
from typing import Any, ClassVar, Dict, List

import numpy as np
import pytest

from predicators import utils
from predicators.approaches.agent_sim_learning_approach import \
    AgentSimLearningApproach
from predicators.code_sim_learning.base_simulator import base_simulator_class
from predicators.code_sim_learning.fit_space import ParamSpec
from predicators.ground_truth_models.balloons.gt_simulator_env import \
    BalloonsResidualEnv
from predicators.structs import Action, LowLevelTrajectory


class _MemoryModel(BalloonsResidualEnv):
    """A small recurrent model with engine physics and an observable
    counter."""

    AGENT_PARAM_SPECS: ClassVar[List[Any]] = [
        ParamSpec("rate", .25, lo=.1, hi=1.0)
    ]
    MODEL_STATE_INIT: ClassVar[Dict[str, Any]] = {
        "charge": 0.0,
        "events": [],
    }

    @classmethod
    def update_model_state(cls, observation, model_state, params, action):
        """The same observation-conditioned update in simulation and play."""
        assert observation.privileged is None
        assert observation.simulator_state is None
        assert action is not None
        model_state["charge"] += params["rate"]
        model_state["events"].append(model_state["charge"])

    def _domain_specific_step(self):
        """No extra body dynamics in this memory-only example."""


@pytest.mark.parametrize("supplied", [False, True])
def test_subclass_state_branches_and_execution_agree(supplied):
    """Loadable subclass memory reaches planning and real execution equally."""
    utils.reset_config({
        "env": "pybullet_balloons",
        "seed": 0,
        "skill_phase_use_motion_planning": False,
    })
    model_cls = _MemoryModel
    if supplied:
        model_cls = type(
            "MemoryModel", (base_simulator_class("pybullet_balloons"), ), {
                "AGENT_PARAM_SPECS": _MemoryModel.AGENT_PARAM_SPECS,
                "MODEL_STATE_INIT": _MemoryModel.MODEL_STATE_INIT,
                "update_model_state":
                _MemoryModel.__dict__["update_model_state"],
            })
    env = model_cls(use_gui=False)
    try:
        # The level is known rather than generated by expensive oracle probes.
        from predicators.envs.pybullet_balloons import \
            PyBulletBalloonsEnv  # pylint: disable=import-outside-toplevel
        source = PyBulletBalloonsEnv(use_gui=False)
        try:
            initial = source.level_state(0, [0, 1], (.7, .75))
            source._set_state(initial)
            initial = source._get_state()
        finally:
            source.dispose()
        action = Action(np.array(initial.joint_positions, dtype=np.float32))
        approach = AgentSimLearningApproach.__new__(AgentSimLearningApproach)
        approach._residual_env_cls = model_cls
        approach._residual_rules = []
        approach._fitted_params = {"rate": .25}
        approach._latent_init = None
        tracker = approach.make_latent_tracker()
        assert tracker is not None
        assert approach._latent_tracking_available()
        start = tracker.attach(initial, None)
        assert start.latent == {"charge": 0.0, "events": []}
        assert initial.latent is None
        predicted = env.simulate(initial, action)
        observed = tracker.attach(predicted, action)
        assert predicted.latent == observed.latent == {
            "charge": .25,
            "events": [.25]
        }
        second = env.simulate(predicted, action)
        assert second.latent == {"charge": .5, "events": [.25, .5]}
        approach._fit_trajectories = [
            LowLevelTrajectory([initial, predicted, second], [action, action])
        ]
        fitted_data = approach._rollout_fit_trajectories({"clip": ["is_on"]})
        assert len(fitted_data) == 1 and len(fitted_data[0][1]) == 2
        # Same physical state, different memory: sibling branches must not
        # inherit one another's state even when State.allclose says they match.
        sibling = predicted.copy()
        sibling.latent = {"charge": 2.0, "events": [2.0]}
        branch = env.simulate(sibling, action)
        assert branch.latent == {"charge": 2.25, "events": [2.0, 2.25]}
        assert predicted.latent == {"charge": .25, "events": [.25]}
        assert not _MemoryModel.MODEL_STATE_INIT["events"]
        snapshot = copy.deepcopy(branch.latent)
        env._set_state(branch)
        assert env._get_state().latent == snapshot
        restored = pickle.loads(pickle.dumps(branch))
        assert env.simulate(restored, action).latent["charge"] == 2.5
        # A replacement physical-parameter dict is visible to existing
        # trackers, including classifiers already holding a memory snapshot.
        approach._identified_physical_params = {"rate": .5}
        tracked = tracker.attach(second, action)
        assert tracked.latent["charge"] == .75
        assert observed.latent["charge"] == .25
        tracker.reset()
        assert tracker.attach(initial, None).latent == {
            "charge": 0.0,
            "events": []
        }
    finally:
        env.dispose()
