# Config file for the main approach and derived oracle, baselines.
---
APPROACHES:
  # oracle_invention: # Oracle 1: NSP explore, GT invention, NSP evaluation
  #   NAME: "vlm_online_invention"
  #   FLAGS:
  #     log_file: "logs/logs_oracle1/"
  #     strips_learner: "cluster_intersect_and_search"
  #     render_init_state: True # True for NSP
  #     neu_sym_predicate: True # Needed for NSP
  #     vlm_predicator_render_option_state: True # Needed for NSP
  #     vlm_predicator_oracle_base_grammar: True
  #     vlm_predicator_oracle_learned: True # Oracle 1
  #     max_initial_demos: 0
  # oracle_explore: # Oracle 2: GT explore, NSP invention, NSP eval.
  #   NAME: "vlm_online_invention"
  #   FLAGS:
  #     log_file: "logs/logs_oracle2/"
  #     strips_learner: "cluster_intersect_and_search"
  #     render_init_state: True # True for NSP
  #     neu_sym_predicate: True # Needed for NSP
  #     vlm_predicator_render_option_state: True # Needed for NSP
  #     vlm_predicator_oracle_explore: True
  nsp-nl: # Our updated main approach
    NAME: "vlm_online_invention"
    FLAGS:
      log_file: "logs/logs_nsp_nl/"
      strips_learner: "cluster_intersect_and_search"
      render_init_state: True # True for NSP
      neu_sym_predicate: True # Needed for NSP
      vlm_predicator_render_option_state: True # Needed for NSP
      max_initial_demos: 0
      vlm_invention_propose_nl_properties: True
      vlm_invention_alternate_between_p_ad: True
      vlm_invention_initial_concept_invention: True
      vlm_invention_use_concept_predicates: True
  # nsp: # Our main approach
  #   NAME: "vlm_online_invention"
  #   FLAGS:
  #     log_file: "logs/logs_nsp/"
  #     strips_learner: "cluster_intersect_and_search"
  #     render_init_state: True # True for NSP
  #     neu_sym_predicate: True # Needed for NSP
  #     vlm_predicator_render_option_state: True # Needed for NSP
  #     max_initial_demos: 0
  # InterPreT-inspired baseline with symbolic predicates based on object 
  # features, conditioned on image and object-oriented dict observation.
  # interpret: 
  #   NAME: "vlm_online_invention"
  #   FLAGS:
  #     log_file: "logs/logs_bs_interpret/"
  #     strips_learner: "cluster_intersect_and_search"
  #     render_init_state: True # True for NSP
  #     neu_sym_predicate: False # Needed for NSP
  #     vlm_predicator_render_option_state: True # Needed for NSP
  #     max_initial_demos: 0
  #     precondition_search_algorithm: "hill_climbing"
  #     vlm_model_name: "gemini-1.5-pro"
  # no_acc_select: # ablation 1: without the new refinement objective
  #   NAME: "vlm_online_invention"
  #   FLAGS:
  #     log_file: "logs/logs_abl_no_acc_select/"
  #     strips_learner: "cluster_intersect_and_search"
  #     render_init_state: True # True for NSP
  #     neu_sym_predicate: True # Needed for NSP
  #     vlm_predicator_render_option_state: True # Needed for NSP
  #     skip_selection_if_no_solve: True
  #     max_initial_demos: 0
  # no_new_op_learner: # ablation 2: without the new operator learner
  #   NAME: "vlm_online_invention"
  #   FLAGS:
  #     log_file: "logs/logs_abl_no_new_op_lrn/"
  #     render_init_state: True # True for NSP
  #     neu_sym_predicate: True # Needed for NSP
  #     vlm_predicator_render_option_state: True # Needed for NSP
  #     max_initial_demos: 0
  #     vlm_invention_propose_nl_properties: True
  #     vlm_invention_alternate_between_p_ad: True
  #     vlm_invention_initial_concept_invention: True
  #     vlm_invention_use_concept_predicates: True
ENVS:
  # pb_cover:
  #   NAME: "pybullet_cover_typed_options"
  #   FLAGS:
  #     pretrained_model_prompt_cache_dir: "pretrained_model_cache/cover"
  #     num_train_tasks: 5 #0 # pybullet_coffee, cover
  #     excluded_predicates: "all"
  #     cover_typed_options_no_sampler: True
  #     cover_initial_holding_prob: 0.0
  #     pybullet_camera_width: 800
  # pb_blocks:
  #   NAME: "pybullet_blocks"
  #   FLAGS:
  #     pretrained_model_prompt_cache_dir: "pretrained_model_cache/blocks"
  #     num_train_tasks: 40 #0 # pybullet_coffee, cover
  #     excluded_predicates: "all"
  #     pybullet_camera_width: 800
  #     vlm_model_name: "gemini-1.5-pro"
  #     grammar_search_search_algorithm: "gbfs" # "hill_climbing"
  #     sesame_check_dr_reachable: False
  #     sesame_filter_unreachable_nsrt: False
  #     disable_harmlessness_check: True
  #     enable_harmless_op_pruning: False
  # pb_coffee:
  #   NAME: "pybullet_coffee"
  #   FLAGS:
  #     pretrained_model_prompt_cache_dir: "pretrained_model_cache/coffee"
  #     num_train_tasks: 5 #0 # pybullet_coffee, cover
  #     excluded_predicates: "Holding,JugInMachine,MachineOn,OnTable,HandEmpty,RobotAboveCup,JugAboveCup,NotAboveCup,PressingButton,Twisting,NotSameCup,JugPickable"
  #     coffee_num_cups_train: '[1]'
  #     coffee_twist_sampler: False
  #     coffee_rotated_jug_ratio: 0.5
  #     coffee_combined_move_and_twist_policy: True
  #     coffee_mac_requires_jug_to_turn_on: True
  #     pybullet_camera_width: 1200 # 1200 for coffee
  pb_cover_w:
    NAME: "pybullet_cover_weighted"
    FLAGS:
      pretrained_model_prompt_cache_dir: "pretrained_model_cache/cover"
      num_train_tasks: 10 #0 # pybullet_coffee, cover
      # excluded_predicates: "IsLight"
      excluded_predicates: "all"
      cover_typed_options_no_sampler: True
      cover_initial_holding_prob: 0.0
      cover_weighted_ratio: 0.5
      pybullet_camera_width: 800
      cover_num_blocks_train: 2
      cover_num_targets_train: 2
      cover_block_widths: "[0.04,0.04,0.04]"
      cover_target_widths: "[0.02,0.02,0.02]"
      vlm_model_name: "gemini-1.5-pro-exp-0801"
  # pb_balance:
  #   NAME: "pybullet_balance"
  #   FLAGS:
  #     pretrained_model_prompt_cache_dir: "pretrained_model_cache/balance"
  #     excluded_predicates: "Balanced,OnPlate"
  #     pybullet_camera_width: 800
  #     num_train_tasks: 10
  #     sesame_check_dr_reachable: False
  #     sesame_filter_unreachable_nsrt: False
  #     # The following two are configured temperarily just for this environment.
  #     disable_harmlessness_check: True
  #     enable_harmless_op_pruning: False
  #     sesame_max_samples_per_step: 1
  #     use_old_nsrt_if_new_is_worse: True
  #     vlm_invention_max_invent_ite: 5
  #     # Uncomment when using the main, comment out when using interpret
  #     vlm_model_name: "gemini-1.5-pro-exp-0801" 
ARGS:
  - "debug"
FLAGS:
  timeout: 1000 #300
  pybullet_control_mode: "reset" # need for blocks and coffee

  # Approach
  env_include_bbox_features: True
  sesame_check_expected_atoms: False
  option_learner: no_learning
  sampler_learner: oracle
  CIS_use_other_pnads_neg_data: True
  # grammar_search_search_algorithm: "gbfs" # "hill_climbing"
  grammar_search_search_algorithm: "hill_climbing" # "hill_climbing"
  grammar_search_grammar_use_single_feature: False
  grammar_search_grammar_use_skip_grammar: False
  grammar_search_grammar_includes_negation:  # relaxation 2
  grammar_search_grammar_includes_foralls: False  # relaxation 2
  grammar_search_prune_redundant_preds: False

  load_vlm_pred_invent_dataset: False
  save_vlm_pred_invent_dataset: False # can't pickle rendered states
  reset_optn_state_dict_at_every_ite: False
  vlm_predicator_use_grammar: True # always true?
  vlm_predicator_oracle_base_grammar: False
  nsp_pred_include_prev_state_in_prompt: True
  nsp_pred_include_prev_image_in_prompt: True
  nsp_pred_include_state_str_in_prompt: False
  vlm_invent_predicates_in_stages: True
  vlm_invent_from_trajs: False
  vlm_invention_positive_negative_include_next_state: True
  save_nsp_image_patch_before_query: False
  vlm_model_name: "gemini-1.5-pro"
  # vlm_model_name: "gpt-4o"
  vlm_temperature: 0
  vlm_use_chat_mode: True
  query_vlm_for_each_assertion: False
  query_vlm_for_each_predicate: False
  vlm_openai_max_response_tokens: 4096
  # pybullet_camera_width: 900 # 900 for cover and blocks
  pybullet_camera_height: 900
START_SEED: 1
NUM_SEEDS: 3