# Use VLM to propose predicates.
---
APPROACHES:
  learn_all:
    NAME: "oracle"
    FLAGS: []
ENVS:
  env_name:
    # NAME: "stick_button"
    # NAME: "stick_button_move"
    # NAME: "blocks"
    # NAME: "pybullet_blocks"
    # NAME: "painting"
    # NAME: "tools"
    # NAME: "coffee"
    NAME: "pybullet_coffee"
ARGS: 
  []
  # - "debug"
  # - "rgb_observation" # stick_button doesn't support rendering
  # - "make_failure_videos"
  # - "make_test_videos"
  # - "make_demo_videos" 
FLAGS:
  num_test_tasks: 20
  excluded_predicates: "all"
  sesame_check_expected_atoms: False

  pybullet_camera_width: 900
  pybullet_camera_height: 900
  video_fps: 20

  # Env specific
  pybullet_control_mode: "reset"
  # bilevel_plan_without_sim: True
  coffee_twist_sampler: False
  kitchen_use_perfect_samplers: True
START_SEED: 2
NUM_SEEDS: 1
...
