# VLM Predicate Use oracle to generate demos
---
APPROACHES:
  learn_all:
    NAME: "oracle"
    FLAGS: []
ENVS:
  stick_button:
    # NAME: "stick_button"
    # NAME: "stick_button_move"
    # NAME: "cover_place_hard"
    # NAME: "blocks"
    # NAME: "cover_multistep_options"
    # NAME: "doors"
    # NAME: "painting"
    # NAME: "tools"
    # NAME: "coffee"
    # NAME: "sticky_table"
    NAME: "pybullet_blocks"
    # NAME: "kitchen"
    # NAME: "burger"
ARGS: 
  # []
  - "debug"
  # - "make_failure_videos"
  # - "make_test_videos"
  # - "make_segmented_demo_videos"
  - "make_demo_videos" 

FLAGS:
  num_train_tasks: 5
  num_test_tasks: 5
  option_learner: no_learning # include all options by flagging no learning
  # kitchen_use_perfect_samplers: True
  # bilevel_plan_without_sim: True
  min_perc_data_for_nsrt: 1
  video_fps: 20

  sesame_check_expected_atoms: False

START_SEED: 2
NUM_SEEDS: 1
...
