"""Compose paper figures from archived simulator renders and verified
results."""
import base64
import hashlib
import io
import json
import math
import os
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any, Dict, Iterable, Optional, Sequence, Tuple

# Optional figure-authoring dependency, separate from benchmark runtime.
import cairosvg  # type: ignore[import-not-found] # pylint: disable=import-error
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent
PAPER = Path(
    os.environ.get("EMPIRIC_PAPER_ROOT",
                   str(ROOT.parents[2] / "sim-predicator-paper"))).resolve()
FIG = ROOT / "figures"
OUTPUT = PAPER / "figures"
DOMAINS = ["Domino", "Bridge", "Balloons", "Boil", "Fan"]
INK, MUTED = "#203744", "#5b6e79"
TEAL, RUST, GREEN = "#087f8c", "#bd5929", "#397957"
NS = "http://www.w3.org/2000/svg"
USED_IMAGES = set()
ET.register_namespace("", NS)
# Crops retain task objects and their surroundings in 900-pixel renders.
CROPS = {
    "boil": (190, 185, 890, 830),
    "domino": (0, 145, 710, 850),
    "fan": (270, 150, 900, 745),
    "bridge": (220, 200, 880, 850),
    "balloons": (280, 350, 890, 800),
}


class Drawing:
    """SVG composition with raster panels and PDF/PNG export."""

    def __init__(self, height: float) -> None:
        self.height = height
        self.root = ET.Element(f"{{{NS}}}svg", {
            "width": "528",
            "height": str(height),
            "viewBox": f"0 0 528 {height}"
        })
        self.root.append(
            ET.Comment(
                " Generated by scripts/build_figures.py; do not edit. "))
        self.add("rect", x=0, y=0, width=528, height=height, fill="white")

    def add(self, tag: str, **kw: Any) -> ET.Element:
        """Append an SVG element."""
        return ET.SubElement(
            self.root, f"{{{NS}}}{tag}",
            {k.replace("_", "-"): str(v)
             for k, v in kw.items()})

    def text(self,
             x: float,
             y: float,
             text: str,
             size: float = 10.5,
             color: str = INK,
             weight: str = "normal",
             anchor: str = "start",
             mono: bool = False) -> None:
        """Place one text label."""
        e = self.add("text",
                     x=x,
                     y=y,
                     font_family="DejaVu Sans Mono" if mono else "DejaVu Sans",
                     font_size=size,
                     fill=color,
                     font_weight=weight,
                     text_anchor=anchor)
        if mono:
            e.set("{http://www.w3.org/XML/1998/namespace}space", "preserve")
        e.text = text

    def lines(self,
              x: float,
              y: float,
              lines: Sequence[str],
              size: float = 10.5,
              color: str = INK,
              leading: float = 15,
              mono: bool = False) -> None:
        """Place evenly spaced text lines."""
        for i, line in enumerate(lines):
            self.text(x, y + leading * i, line, size, color, mono=mono)

    def rect(self,
             x: float,
             y: float,
             w: float,
             h: float,
             fill: str = "#f4f7f8",
             stroke: str = "#d3dde1",
             radius: float = 5,
             dash: Optional[str] = None) -> None:
        """Draw a rounded rectangle."""
        kw: Dict[str, Any] = dict(x=x,
                                  y=y,
                                  width=w,
                                  height=h,
                                  rx=radius,
                                  fill=fill,
                                  stroke=stroke,
                                  stroke_width=.8)
        if dash:
            kw["stroke_dasharray"] = dash
        self.add("rect", **kw)

    def arrow(self,
              x1: float,
              y1: float,
              x2: float,
              y2: float,
              color: str = MUTED) -> None:
        """Draw a directed connector."""
        self.add("path",
                 d=f"M{x1} {y1} L{x2} {y2}",
                 fill="none",
                 stroke=color,
                 stroke_width=1.3)
        dx, dy = x2 - x1, y2 - y1
        length = math.hypot(dx, dy)
        ux, uy = dx / length, dy / length
        points = [(x2, y2), (x2 - 5 * ux - 2.5 * uy, y2 - 5 * uy + 2.5 * ux),
                  (x2 - 5 * ux + 2.5 * uy, y2 - 5 * uy - 2.5 * ux)]
        self.add("polygon",
                 points=" ".join(f"{x},{y}" for x, y in points),
                 fill=color)

    def photo(self,
              name: str,
              x: float,
              y: float,
              w: float,
              h: float,
              crop: Optional[Tuple[int, int, int, int]] = None,
              contain: bool = False,
              gui_key: Optional[str] = None) -> None:
        """Embed a cropped source photograph."""
        gui_manifest = ROOT / "data/gui-figure-manifest.json"
        gui_panel = None
        if gui_manifest.exists():
            gui_panel = json.loads(gui_manifest.read_text())["lookup"].get(
                gui_key or f"{self.height}:{x}:{y}")
        if gui_panel:
            sources = [ROOT / gui_panel]
            crop = None
        else:
            sources = [
                p for p in (FIG / "sources").glob(f"{name}.*")
                if p.suffix.lower() in {'.png', '.jpg', '.jpeg'}
            ]
        # Local GUI re-renders can replace pixels without changing panel IDs,
        # archived evidence, or the layout. Never silently overwrite sources.
        overrides = ROOT / "data/figure-render-overrides.json"
        if overrides.exists():
            USED_IMAGES.add(overrides)
            replacements = json.loads(overrides.read_text())
            replacement = replacements.get(gui_key) or replacements.get(name)
            if replacement:
                sources = [ROOT / replacement["path"]]
                crop = replacement.get("crop")
        assert len(sources) == 1, (name, sources)
        USED_IMAGES.add(sources[0])
        im = Image.open(sources[0]).convert("RGB")
        if crop is not None:
            im = im.crop(crop)
        size = (round(w * 4), round(h * 4))
        if contain:
            im = ImageOps.pad(im,
                              size,
                              method=Image.Resampling.LANCZOS,
                              color="#f4f7f8")
        else:
            im = ImageOps.fit(im, size, method=Image.Resampling.LANCZOS)
        stream = io.BytesIO()
        im.save(stream, format="PNG")
        self.add("image",
                 x=x,
                 y=y,
                 width=w,
                 height=h,
                 href="data:image/png;base64," +
                 base64.b64encode(stream.getvalue()).decode())

    def scene(self,
              domain: str,
              state: str,
              x: float,
              y: float,
              w: float,
              h: float,
              gui_key: Optional[str] = None) -> None:
        """Embed a domain render, including the updated Balloons assets."""
        if domain == "Balloons":
            self.photo(f"balloons_refined_{state}",
                       x,
                       y,
                       w,
                       h,
                       crop=(240, 260, 1050, 790),
                       gui_key=gui_key)
        else:
            self.photo(f"{domain.lower()}_{state}",
                       x,
                       y,
                       w,
                       h,
                       crop=CROPS[domain.lower()],
                       gui_key=gui_key)

    def save(self, name: str) -> None:
        """Write vector, PDF, and raster versions."""
        raw = ET.tostring(self.root, encoding="utf-8", xml_declaration=True)
        (OUTPUT / f"{name}.svg").write_bytes(raw)
        cairosvg.svg2pdf(bytestring=raw, write_to=str(OUTPUT / f"{name}.pdf"))
        cairosvg.svg2png(bytestring=raw,
                         write_to=str(OUTPUT / f"{name}.png"),
                         scale=2)


def teaser() -> None:
    """Render the overview teaser."""
    d = Drawing(363)
    d.text(0,
           14,
           "Learn missing physics as programs, then use them to solve",
           12.8,
           weight="bold")
    for x, title, color in [(0, "Discover hidden physics", RUST),
                            (184, "Program a simulator", TEAL),
                            (368, "Predict and solve", GREEN)]:
        d.rect(x, 27, 160, 127, fill="#f7f9fa", stroke="#d9e2e7")
        d.text(x + 8, 45, title, 10.4, color, "bold")
    d.photo("bridge_wet_lift", 8, 54, 68, 64, gui_key="304:7:57")
    d.photo("bridge_bonded_lift", 84, 54, 68, 64, gui_key="304:87:57")
    d.text(42, 132, "One lifts", 9.5, RUST, anchor="middle")
    d.text(118, 132, "All lift", 9.5, GREEN, anchor="middle")
    d.text(80,
           146,
           "Contact time changes the outcome.",
           8.4,
           MUTED,
           anchor="middle")
    d.text(192, 63, "Illustrative simulator extension", 8.1, MUTED)
    d.lines(192,
            80, [
                "class Glue(BaseSimulator):", "  def residual_step(self):",
                "    update_contact_age()", "    if age > cure_time:",
                "      add_bond_constraint()"
            ],
            7.7,
            color=TEAL,
            leading=11,
            mono=True)
    d.text(192, 146, "Fit the program to observations.", 8.5)
    d.photo("bridge_exec_04_done", 376, 54, 144, 78, gui_key="304:370:57")
    d.text(448,
           146,
           "Rehearse, then complete the bridge.",
           8.5,
           anchor="middle")
    d.arrow(163, 92, 181, 92)
    d.arrow(347, 92, 365, 92)
    mechanisms = [
        "Contact & friction", "Curing & bonds", "Lift & damping",
        "Filling & heat", "Wind-driven motion"
    ]
    source_order = ["Boil", "Domino", "Fan", "Bridge", "Balloons"]
    for center, label in [(219, "Initial scenes"), (302, "After execution")]:
        d.text(0, 0, label, 9.6, MUTED, anchor="middle")
        d.root[-1].set("transform", f"translate(11 {center}) rotate(-90)")
    for i, (domain, mechanism) in enumerate(zip(DOMAINS, mechanisms)):
        x = 23 + i * 102
        source_x = source_order.index(domain) * 107
        d.text(x + 48.5, 169, domain, 10.6, TEAL, "bold", anchor="middle")
        d.scene(domain, "start", x, 177, 97, 83, gui_key=f"281:{source_x}:18")
        d.scene(domain, "win", x, 261, 97, 83, gui_key=f"281:{source_x}:136")
        d.text(x + 48.5, 358, mechanism, 8.7, MUTED, anchor="middle")
    d.save("fig1_residual")


def pipeline() -> None:
    """Render the learning and planning workflow."""
    d = Drawing(321)
    d.text(0,
           14,
           "EMPIRIC: an agent-directed learning and planning loop",
           12.8,
           weight="bold")
    panels = [
        (0, 29, "1  Explore", RUST,
         ["Interact and observe", "noisy physical outcomes."]),
        (184, 29, "2  Hypothesize", TEAL, [
            "Propose missing mechanisms.", "Write or revise simulator code.",
            "Base physics + learned residual"
        ]),
        (368, 29, "3  Design experiment", RUST, [
            "Compare predicted outcomes.", "Choose a probe that resolves",
            "decision-relevant uncertainty."
        ]),
        (368, 178, "4  Execute", RUST, [
            "Apply skills in the environment.",
            "Save actions and observations."
        ]),
        (184, 178, "5  Learn & model", TEAL, [
            "Fit the simulator to recordings.",
            "Infer parameters + initial states.", "Estimate the current state."
        ]),
        (0, 178, "6  Plan & solve", GREEN, [
            "Rehearse candidate plans", "under parameter uncertainty.",
            "Execute; check the outcome."
        ]),
    ]
    for x, y, title, color, lines in panels:
        d.rect(x, y, 160, 104, fill="#f7f9fa", stroke="#d9e2e7")
        d.text(x + 8, y + 19, title, 10.8, color, "bold")
        d.lines(x + 8, y + 40, lines, 9.1, leading=14)
    # Compact visual anchors distinguish the environment from inference.
    d.scene("Bridge", "start", 8, 91, 50, 34, gui_key="281:321:18")
    d.text(66, 112, "Experience D", 9.4, RUST)
    d.text(192, 120, "simulator.py", 9.5, TEAL, mono=True)
    d.photo("bridge_wet_lift", 376, 240, 50, 34, gui_key="304:7:57")
    d.text(434, 261, "New evidence", 9.1, RUST)
    d.text(192, 269, "Joint posterior + state estimate", 8.5, TEAL)
    d.text(8, 269, "Solved → next task", 9.2, GREEN, weight="bold")
    for start, end in [(160, 184), (344, 368)]:
        d.arrow(start + 3, 80, end - 3, 80)
        d.arrow(end - 3, 231, start + 3, 231)
    d.arrow(477, 137, 477, 174)
    d.text(282,
           150,
           "Uncertain or prediction mismatch?",
           9,
           TEAL,
           anchor="middle")
    d.add("path",
          d="M80 174 L80 159 L420 159 L420 143",
          fill="none",
          stroke=TEAL,
          stroke_width=1.3)
    d.arrow(420, 143, 420, 137, color=TEAL)
    d.text(264,
           302, "Persistent workspace: recordings, simulator programs, "
           "beliefs, journal",
           9.8,
           weight="bold",
           anchor="middle")
    d.text(264,
           317, "Training: steps + resets    |    "
           "Testing: steps only; learning continues",
           9.2,
           MUTED,
           anchor="middle")
    d.save("fig2_continual")


def environments() -> None:
    """Figure 3 now shows recorded execution, not the domain gallery."""
    archive = ROOT / "data/trajectories/figure3.json"
    USED_IMAGES.add(archive)
    rows = json.loads(archive.read_text())["rows"]
    d = Drawing(234)
    for row_index, row in enumerate(rows):
        y = row_index * 119
        title = d.add("text",
                      x=0,
                      y=0,
                      font_family="DejaVu Sans",
                      font_size=11,
                      fill=TEAL,
                      font_weight="bold",
                      text_anchor="middle",
                      transform=f"translate(12 {y+49}) rotate(-90)")
        title.text = row["domain"]
        for i, frame in enumerate(row["frames"]):
            source = FIG / "sources" / (frame["name"] + ".png")
            assert hashlib.sha256(
                source.read_bytes()).hexdigest() == frame["sha256"]
            x = 24 + i * 103
            d.photo(frame["name"],
                    x,
                    y,
                    92,
                    98,
                    crop=row["crop"],
                    gui_key=frame["name"])
            d.text(x + 46,
                   y + 111,
                   f"{frame['label']} · t={frame['level_step']:,}",
                   7.3,
                   anchor="middle")
            if i < 4:
                d.arrow(x + 94, y + 49, x + 101, y + 49)
    d.save("fig4_environments")


def build_overview_figures() -> None:
    """Rebuild Figures 1 and 3; Figure 2 is maintained in Figma."""
    OUTPUT.mkdir(parents=True, exist_ok=True)
    USED_IMAGES.clear()
    teaser()
    environments()
    inputs = USED_IMAGES | {
        Path(__file__), ROOT / "data/gui-figure-manifest.json"
    }
    outputs = [
        OUTPUT / f"{name}.{ext}"
        for name in ("fig1_residual", "fig4_environments")
        for ext in ("pdf", "svg", "png")
    ]

    def hashes(paths: Iterable[Path], base: Path) -> Dict[str, str]:
        return {
            str(p.relative_to(base)):
            hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(paths)
        }

    (ROOT / "data/overview-figure-build-manifest.json").write_text(
        json.dumps(
            {
                "generated_by":
                "scripts/paper_figures/build_figures.py --overview; "
                "do not edit manually",
                "inputs":
                hashes(inputs, ROOT),
                "outputs":
                hashes(outputs, OUTPUT)
            },
            indent=2) + "\n")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--overview", action="store_true", required=True)
    parser.parse_args()
    build_overview_figures()
