#!/usr/bin/env bash
# Run one rung of the domino-fan ladder. No YAML editing.
#
#   scripts/domino_fan/run_rung.sh 1     # oracle           ~2 min, no LLM
#   scripts/domino_fan/run_rung.sh 2     # agent plans      ~15 min
#   scripts/domino_fan/run_rung.sh 3     # learns wind params
#   scripts/domino_fan/run_rung.sh 4     # learns wind code + predicates
#   scripts/domino_fan/run_rung.sh all   # 1 then 2 then 3 then 4
#
# Add --declare for the button-free variant, where the robot runs
# DeclareFinished instead of pressing a switch:
#
#   scripts/domino_fan/run_rung.sh --declare 1
#
# --blow is the place-it-so-the-wind-carries-it task, where the wind's
# strength IS fittable and rung 3 is therefore worth running:
#
#   scripts/domino_fan/run_rung.sh --blow 1
#
# SEED=1 repeats a rung on another seed, for a second opinion:
#
#   SEED=1 scripts/domino_fan/run_rung.sh 4
#
# Each rung gives the agent less and asks it to recover more:
#   1  GT simulator + GT predicates, process planner plans.
#   2  GT simulator + GT predicates, the AGENT plans.
#   3  GT simulator STRUCTURE, its parameters fitted from data.
#   4  Base simulator only: discover the wind, model it, invent predicates.
#
# Results land in logs/<approach>/rung<N>_*/ and videos/<same>/, and show
# up in the dashboard (scripts/domino_fan/dashboard.sh).
set -euo pipefail
cd "$(dirname "$0")/../.."

PY=".venv/bin/python"
[ -x "$PY" ] || PY="python3"

usage() { sed -n '2,24p' "$0" | sed 's/^# \{0,1\}//'; exit 1; }

# Which env the ladder runs on. Same arms, same rungs; only the thing
# that starts the fan differs.
ENV_KEY="domino_fan"
if [ "${1:-}" = "--declare" ]; then
  ENV_KEY="domino_declare"
  shift
elif [ "${1:-}" = "--blow" ]; then
  ENV_KEY="domino_blow"
  shift
fi

# Which random seed to run. A rung's result on one seed is an anecdote:
# the agent's exploration is not deterministic, so a repeat with a
# different seed is the cheapest evidence that a result is the method
# rather than the draw. Runs land in seed<N>/ and show as separate rows.
SEED="${SEED:-0}"
[ $# -ge 1 ] || usage

run_one() {
  local rung="$1" arm exp
  case "$rung" in
    1) arm="oracle"                          ; exp="rung1_oracle" ;;
    2) arm="agent_model_based_planning"      ; exp="rung2_agent_planner" ;;
    3) arm="agent_param_learning"            ; exp="rung3_param_learning"
       echo "NOTE: rung 3 fits the wind's parameters, and in this env they" >&2
       echo "      are not identifiable: the wind acts for ~2 steps before" >&2
       echo "      the start block tips, so the whole observation is 'tipped" >&2
       echo "      or did not'. 1.5 N and 2.0 N give identical trajectories." >&2
       echo "      Rung 4 learns the wind RULE instead, which is the open" >&2
       echo "      question here. Running anyway." >&2 ;;
    4) arm="agent_po_predicate_invention_al" ; exp="rung4_full_learning" ;;
    *) echo "unknown rung: $rung" >&2; usage ;;
  esac

  # experiment_id is built by cluster_utils as "<env key>-<arm key>",
  # so it is domino_fan-<arm>; the dashboard maps that back to a rung.
  local cfg="scripts/configs/predicatorv3/_${ENV_KEY}_rung${rung}_s${SEED}.yaml"
  # Generated, not hand-edited: every arm parked except this one.
  $PY - "$rung" "$arm" "$ENV_KEY" "$SEED" > "$cfg" <<'PYEOF'
import sys
rung, arm, env_key, seed = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
arms = ["oracle", "agent_model_based_planning", "agent_param_learning",
        "agent_po_predicate_invention_al"]
lines = [
    f"# GENERATED by scripts/domino_fan/run_rung.sh for rung {rung}.",
    "# Edit run_rung.sh, not this file - it is overwritten on every run.",
    "---",
    "includes:",
    "  - common.yaml",
    "  - envs/all.yaml",
    "  - approaches/all.yaml",
    f"START_SEED: {seed}",
    "NUM_SEEDS: 1",
    "ENVS:",
    f"  {env_key}:",
    "    SKIP: False",
    "APPROACHES:",
]
for a in arms:
    lines += [f"  {a}:", f"    SKIP: {a != arm}"]
    if a != arm:
        continue
    flags = [
        # approaches/all.yaml sets option_model_use_gui: True on
        # agent_param_learning (and on agent_sim_learning and
        # agent_oracle_mono_sim). That opens a REAL PyBullet GUI client
        # per option-model env, and this ladder rebuilds that env many
        # times over a run: rung 3 had ten 1024x796 windows open in one
        # process before it was half done. Useful when a person is
        # watching a rollout, pure cost for a batch run started from a
        # script or a dashboard button, where nobody is.
        "      option_model_use_gui: False",
    ]
    if a == "agent_model_based_planning":
        # Nothing to learn with a GT model, so online cycles only
        # re-derive a solved plan at ~$2/cycle. Matches what
        # agent_oracle_hybrid_sim already does.
        flags.append("      num_online_learning_cycles: 0")
    elif a.startswith("agent_p"):
        flags.append("      skip_initial_test: True")
    if a == "agent_po_predicate_invention_al":
        # Rung 4 spent 5 hours inside cycle 0 and never scored a test.
        # The cost is the rollout fit: the agent declared FIVE physical
        # params (the hand-written GT simulator has two), and the grid
        # seeding is a coordinate sweep - params x seed_points x passes
        # rollout evaluations, each rebuilding a PyBullet env, each
        # replaying every recorded trajectory, run once per refit.
        #
        # Worth cutting because that fit was not buying anything: it
        # reported a Δ of exactly 0.0000 on all five params, five times
        # over, which is the same identifiability wall
        # probe_wind_identifiability.py measures - above the topple
        # threshold the wind's effect saturates and SSE is flat. The
        # discovery this rung is for happens in cycle 0 regardless, and
        # the agent's own initial values already produced reward-0.95
        # episodes in the real env.
        flags += [
            "      num_online_learning_cycles: 2",
            "      code_sim_learning_rollout_grid_seed_points: 5",
            "      code_sim_learning_rollout_grid_sweep_passes: 1",
        ]
    lines += ["    FLAGS:"] + flags
print("\n".join(lines))
PYEOF

  echo "=========================================================="
  echo "  RUNG $rung  ->  $arm   (seed $SEED)"
  echo "  logs/*/${ENV_KEY}-$arm/   (rung $rung: $exp)"
  echo "=========================================================="
  PYTHONHASHSEED=0 $PY scripts/local/launch_simp.py \
      -c "predicatorv3/_${ENV_KEY}_rung${rung}_s${SEED}.yaml"
}

if [ "$1" = "all" ]; then
  for r in 1 2 3 4; do run_one "$r"; done
else
  for r in "$@"; do run_one "$r"; done
fi
