#!/usr/bin/env bash
# Run one rung of the domino-fan ladder. No YAML editing.
#
#   scripts/domino_fan/run_rung.sh 1     # oracle           ~2 min, no LLM
#   scripts/domino_fan/run_rung.sh 2     # agent plans      ~15 min
#   scripts/domino_fan/run_rung.sh 3     # learns wind params
#   scripts/domino_fan/run_rung.sh 4     # learns wind code + predicates
#   scripts/domino_fan/run_rung.sh all   # 1 then 2 then 3 then 4
#
# Each rung gives the agent less and asks it to recover more:
#   1  GT simulator + GT predicates, process planner plans.
#   2  GT simulator + GT predicates, the AGENT plans.
#   3  GT simulator STRUCTURE, its parameters fitted from data.
#   4  Base simulator only: discover the wind, model it, invent predicates.
#
# Results land in logs/<approach>/rung<N>_*/ and videos/<same>/, and show
# up in the dashboard (scripts/domino_fan/dashboard.sh).
set -euo pipefail
cd "$(dirname "$0")/../.."

PY=".venv/bin/python"
[ -x "$PY" ] || PY="python3"

usage() { sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'; exit 1; }
[ $# -ge 1 ] || usage

run_one() {
  local rung="$1" arm exp
  case "$rung" in
    1) arm="oracle"                          ; exp="rung1_oracle" ;;
    2) arm="agent_model_based_planning"      ; exp="rung2_agent_planner" ;;
    3) arm="agent_param_learning"            ; exp="rung3_param_learning"
       echo "NOTE: rung 3 fits the wind's parameters, and in this env they" >&2
       echo "      are not identifiable: the wind acts for ~2 steps before" >&2
       echo "      the start block tips, so the whole observation is 'tipped" >&2
       echo "      or did not'. 1.5 N and 2.0 N give identical trajectories." >&2
       echo "      Rung 4 learns the wind RULE instead, which is the open" >&2
       echo "      question here. Running anyway." >&2 ;;
    4) arm="agent_po_predicate_invention_al" ; exp="rung4_full_learning" ;;
    *) echo "unknown rung: $rung" >&2; usage ;;
  esac

  # experiment_id is built by cluster_utils as "<env key>-<arm key>",
  # so it is domino_fan-<arm>; the dashboard maps that back to a rung.
  local cfg="scripts/configs/predicatorv3/_rung${rung}.yaml"
  # Generated, not hand-edited: every arm parked except this one.
  $PY - "$rung" "$arm" > "$cfg" <<'PYEOF'
import sys
rung, arm = sys.argv[1], sys.argv[2]
arms = ["oracle", "agent_model_based_planning", "agent_param_learning",
        "agent_po_predicate_invention_al"]
lines = [
    f"# GENERATED by scripts/domino_fan/run_rung.sh for rung {rung}.",
    "# Edit run_rung.sh, not this file - it is overwritten on every run.",
    "---",
    "includes:",
    "  - common.yaml",
    "  - envs/all.yaml",
    "  - approaches/all.yaml",
    "ENVS:",
    "  domino_fan:",
    "    SKIP: False",
    "APPROACHES:",
]
for a in arms:
    lines += [f"  {a}:", f"    SKIP: {a != arm}"]
    if a != arm:
        continue
    flags = [
        # approaches/all.yaml sets option_model_use_gui: True on
        # agent_param_learning (and on agent_sim_learning and
        # agent_oracle_mono_sim). That opens a REAL PyBullet GUI client
        # per option-model env, and this ladder rebuilds that env many
        # times over a run: rung 3 had ten 1024x796 windows open in one
        # process before it was half done. Useful when a person is
        # watching a rollout, pure cost for a batch run started from a
        # script or a dashboard button, where nobody is.
        "      option_model_use_gui: False",
    ]
    if a == "agent_model_based_planning":
        # Nothing to learn with a GT model, so online cycles only
        # re-derive a solved plan at ~$2/cycle. Matches what
        # agent_oracle_hybrid_sim already does.
        flags.append("      num_online_learning_cycles: 0")
    elif a.startswith("agent_p"):
        flags.append("      skip_initial_test: True")
    lines += ["    FLAGS:"] + flags
print("\n".join(lines))
PYEOF

  echo "=========================================================="
  echo "  RUNG $rung  ->  $arm"
  echo "  logs/*/domino_fan-$arm/   (rung $rung: $exp)"
  echo "=========================================================="
  PYTHONHASHSEED=0 $PY scripts/local/launch_simp.py -c "predicatorv3/_rung${rung}.yaml"
}

if [ "$1" = "all" ]; then
  for r in 1 2 3 4; do run_one "$r"; done
else
  for r in "$@"; do run_one "$r"; done
fi
