name: predicators

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [3.7, 3.8, 3.9]
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Pytest
      run: |
        pytest tests/
  static-type-checking:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [3.7, 3.8, 3.9]
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mypy
    - name: Mypy
      run: |
        mypy .
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [3.7, 3.8, 3.9]
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-pylint
    - name: Pylint
      run: |
        pytest . --pylint -m pylint --pylint-rcfile=.predicators_pylintrc
